"""
models/proactive_agent.py — SQLAlchemy Models for Proactive AI Sustainability Agent (Step 23 & Improvement Patches).

Provides persistent storage for grounded, deterministic AgentActions and their auditable lifecycle events.
Enforces the single-source-of-priority-truth principle (inherits from Step 22A), queue separation
(REDUCTION vs DATA_QUALITY), dependency graph (parent/blocked/ready), and structured explanation contract.
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Numeric, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from backend.app.database.base import Base


class AgentAction(Base):
    """
    Persisted, deterministic decision action generated by the Proactive AI Sustainability Agent.
    """
    __tablename__ = "agent_actions"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # Scoping & Lineage
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True, index=True)
    action_type = Column(String(100), nullable=False, index=True)
    category = Column(String(50), nullable=False, index=True)  # DATA_QUALITY, ENERGY, FUEL, EMISSIONS, REDUCTION, etc.
    queue_type = Column(String(50), nullable=False, default="REDUCTION", index=True)  # REDUCTION, DATA_QUALITY, GENERAL

    # Single Source of Priority Truth (Patch 1)
    priority = Column(String(50), nullable=False, index=True)  # CRITICAL, HIGH, MEDIUM, LOW, INFORMATIONAL
    priority_score = Column(Numeric(6, 2), nullable=False, default=0.0)
    priority_source = Column(String(100), nullable=False, default="REDUCTION_INTELLIGENCE")  # Subsystem tracking
    deterministic_score = Column(Numeric(10, 2), nullable=True)

    # Action Summary
    title = Column(String(255), nullable=False)
    summary = Column(Text, nullable=False)
    why_it_matters = Column(Text, nullable=False)
    recommended_action = Column(Text, nullable=False)

    # Structured Explanation Contract (Patch 5)
    what = Column(Text, nullable=True)
    why = Column(Text, nullable=True)
    next_step = Column(Text, nullable=True)
    evidence = Column(Text, nullable=True)
    follow_up = Column(Text, nullable=True)
    limitation = Column(Text, nullable=True)

    # Dependency Graph Engine (Patch 3)
    parent_action_id = Column(Integer, ForeignKey("agent_actions.id", ondelete="SET NULL"), nullable=True, index=True)
    blocks_action_id = Column(Integer, ForeignKey("agent_actions.id", ondelete="SET NULL"), nullable=True, index=True)
    dependency_status = Column(String(50), nullable=False, default="NONE", index=True)  # NONE, BLOCKED, READY, COMPLETED

    # Provenance Lineage (Exact source references)
    source_type = Column(String(100), nullable=False, index=True)  # REDUCTION_PRIORITY, ROADMAP_ITEM, SCENARIO, LEDGER_ENTRY, EMISSION_FACTOR, etc.
    source_id = Column(String(100), nullable=True, index=True)
    source_document_id = Column(Integer, nullable=True, index=True)
    reporting_period = Column(String(100), nullable=True)
    metric_value = Column(Numeric(18, 4), nullable=True)
    metric_unit = Column(String(50), nullable=True)
    evidence_reference = Column(Text, nullable=True)

    # Lifecycle & Deduplication (Patch 7)
    status = Column(String(50), nullable=False, default="OPEN", index=True)  # OPEN, IN_PROGRESS, COMPLETED, DISMISSED, EXPIRED
    due_context = Column(String(255), nullable=True)
    dedup_key = Column(String(255), nullable=False, index=True)
    agent_version = Column(String(50), nullable=False, default="1.0")

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    completed_at = Column(DateTime, nullable=True)
    dismissed_at = Column(DateTime, nullable=True)

    # Relationships
    events = relationship("AgentActionEvent", back_populates="action", cascade="all, delete-orphan")

    def __init__(self, **kwargs):
        if "action_queue" in kwargs and "queue_type" not in kwargs:
            kwargs["queue_type"] = kwargs.pop("action_queue")
        if "priority_level" in kwargs and "priority" not in kwargs:
            kwargs["priority"] = kwargs.pop("priority_level")
        if "description" in kwargs and "summary" not in kwargs:
            kwargs["summary"] = kwargs.pop("description")
        if "next" in kwargs and "next_step" not in kwargs:
            kwargs["next_step"] = kwargs.pop("next")
        if "summary" not in kwargs:
            kwargs["summary"] = kwargs.get("title", "")
        if "why_it_matters" not in kwargs:
            kwargs["why_it_matters"] = kwargs.get("why", kwargs.get("title", ""))
        if "recommended_action" not in kwargs:
            kwargs["recommended_action"] = kwargs.get("next_step", kwargs.get("title", ""))
        if "source_type" not in kwargs:
            kwargs["source_type"] = "SYSTEM"
        super().__init__(**kwargs)

    @property
    def action_queue(self):
        return self.queue_type

    @action_queue.setter
    def action_queue(self, val):
        self.queue_type = val

    @property
    def priority_level(self):
        return self.priority

    @priority_level.setter
    def priority_level(self, val):
        self.priority = val

    @property
    def description(self):
        return self.summary

    @description.setter
    def description(self, val):
        self.summary = val

    @property
    def next(self):
        return self.next_step

    @next.setter
    def next(self, val):
        self.next_step = val

    def to_dict(self):
        return {
            "id": self.id,
            "document_id": self.document_id,
            "action_type": self.action_type,
            "category": self.category,
            "queue_type": self.queue_type,
            "action_queue": self.queue_type,
            "priority": self.priority,
            "priority_level": self.priority,
            "priority_score": float(self.priority_score) if self.priority_score is not None else 0.0,
            "priority_source": self.priority_source,
            "deterministic_score": float(self.deterministic_score) if self.deterministic_score is not None else None,
            "title": self.title,
            "summary": self.summary,
            "description": self.summary,
            "why_it_matters": self.why_it_matters,
            "recommended_action": self.recommended_action,
            "what": self.what or self.title,
            "why": self.why or self.why_it_matters,
            "next": self.next_step or self.recommended_action,
            "evidence": self.evidence or self.evidence_reference,
            "follow_up": self.follow_up,
            "limitation": self.limitation,
            "parent_action_id": self.parent_action_id,
            "blocks_action_id": self.blocks_action_id,
            "dependency_status": self.dependency_status,
            "source_type": self.source_type,
            "source_id": self.source_id,
            "source_document_id": self.source_document_id,
            "reporting_period": self.reporting_period,
            "metric_value": float(self.metric_value) if self.metric_value is not None else None,
            "metric_unit": self.metric_unit,
            "evidence_reference": self.evidence_reference,
            "status": self.status,
            "due_context": self.due_context,
            "dedup_key": self.dedup_key,
            "agent_version": self.agent_version,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "dismissed_at": self.dismissed_at.isoformat() if self.dismissed_at else None,
        }


class AgentActionEvent(Base):
    """
    Immutable audit record tracking status transitions and events for an AgentAction.
    """
    __tablename__ = "agent_action_events"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    action_id = Column(Integer, ForeignKey("agent_actions.id", ondelete="CASCADE"), nullable=False, index=True)
    event_type = Column(String(50), nullable=False, index=True)  # CREATED, PRIORITIZED, OPENED, STARTED, COMPLETED, DISMISSED, EXPIRED, REGENERATED
    previous_status = Column(String(50), nullable=True)
    new_status = Column(String(50), nullable=False)
    actor_type = Column(String(50), nullable=False, default="SYSTEM")  # USER, SYSTEM, AGENT
    reason = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    action = relationship("AgentAction", back_populates="events")

    def __init__(self, **kwargs):
        import json
        if "from_status" in kwargs and "previous_status" not in kwargs:
            kwargs["previous_status"] = kwargs.pop("from_status")
        if "to_status" in kwargs and "new_status" not in kwargs:
            kwargs["new_status"] = kwargs.pop("to_status")
        if "actor" in kwargs and "actor_type" not in kwargs:
            kwargs["actor_type"] = kwargs.pop("actor")
        if "details" in kwargs and "reason" not in kwargs:
            det = kwargs.pop("details")
            kwargs["reason"] = json.dumps(det) if isinstance(det, dict) else str(det)
        super().__init__(**kwargs)

    @property
    def from_status(self):
        return self.previous_status

    @from_status.setter
    def from_status(self, val):
        self.previous_status = val

    @property
    def to_status(self):
        return self.new_status

    @to_status.setter
    def to_status(self, val):
        self.new_status = val

    @property
    def actor(self):
        return self.actor_type

    @actor.setter
    def actor(self, val):
        self.actor_type = val

    @property
    def details(self):
        import json
        if not self.reason:
            return {}
        try:
            val = json.loads(self.reason)
            if isinstance(val, dict):
                if "reason" not in val and "note" in val:
                    val["reason"] = val["note"]
                return val
            return {"note": str(val), "reason": str(val)}
        except Exception:
            return {"note": self.reason, "reason": self.reason}

    def to_dict(self):
        return {
            "id": self.id,
            "action_id": self.action_id,
            "event_type": self.event_type,
            "previous_status": self.previous_status,
            "from_status": self.previous_status,
            "new_status": self.new_status,
            "to_status": self.new_status,
            "actor_type": self.actor_type,
            "actor": self.actor_type,
            "reason": self.reason,
            "details": self.details,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
